# Generated by Django 4.0.3 on 2022-05-30 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('update_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='categoryImage/')),
                ('categoryName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('report', models.IntegerField(default=0)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('follower', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('update_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('question', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='miniquiz.category')),
            ],
        ),
        migrations.CreateModel(
            name='leaderboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('score', models.CharField(max_length=1000)),
                ('authorsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorIdentity', to=settings.AUTH_USER_MODEL)),
                ('categoryIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='miniquiz.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('update_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='miniquiz.questions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
