# Generated by Django 4.0.3 on 2022-06-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniquiz', '0002_alter_leaderboards_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
