# Generated by Django 4.0.3 on 2022-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniquiz', '0003_category_categoryimage_alter_answer_update_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('follower', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImage/'),
        ),
    ]
