# Generated by Django 4.0.3 on 2022-06-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniquiz', '0004_alter_leaderboards_authorsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboards',
            name='categoryIdentity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_id', to='miniquiz.category'),
        ),
    ]
