# Generated by Django 4.0.3 on 2022-06-09 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniquiz', '0005_alter_leaderboards_categoryidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboards',
            name='authorsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorIdentity', to=settings.AUTH_USER_MODEL),
        ),
    ]
