# Generated by Django 4.0.3 on 2022-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniquiz', '0006_alter_category_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
