# Generated by Django 4.0.3 on 2022-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_registered_date_account_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_joined',
            new_name='Registered_date',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='date joined'),
        ),
    ]
