# Generated by Django 4.0.3 on 2022-03-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_date_joined_account_registered_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Registered_date',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
