# Generated by Django 4.0.3 on 2022-05-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_is_verified_account_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Email of otp Send')),
                ('validated', models.BooleanField(default=False, help_text='if true then it mean otp is validate')),
                ('otpSessionID', models.CharField(default=None, max_length=120, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('email', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, default=True, max_length=100, null=True)),
            ],
        ),
    ]
